services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: football_clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: football_analytics
      CLICKHOUSE_PASSWORD: football123
    volumes:
      - clickhouse_data:/var/lib/clickhouse

volumes:
  clickhouse_data: